name: Publish Release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    name: "Publish release"
    environment: pypi
    permissions:
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Build project for distribution
      run: uv build

    - name: Publish to PyPI
      run: uv publish
